{% set version = "0.7.0" %}

package:
  name: git-crypt
  version: {{ version }}

source:
  url: https://github.com/AGWA/git-crypt/archive/{{ version }}.tar.gz
  sha256: 2210a89588169ae9a54988c7fdd9717333f0c6053ff704d335631a387bd3bcff
  patches:
    - prefix.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - openssl
  run:
    - git
    - openssl

test:
  commands:
    - git-crypt help status

about:
  home: https://www.agwa.name/projects/git-crypt/
  license: GPL-3.0
  license_file: COPYING
  summary: Transparent file encryption in git

extra:
  recipe-maintainers:
    - ocefpaf
