travis:
  secure:
    BINSTAR_TOKEN: R9K1j30l7WQvMt/AU/Mfq/f9cA/VzvyZbxI7PQEDJVFeb0UC0sDoV7gteInPuAFHkQoT0hwZuWUWSb9yaAZsrTZJHA+1YUTtgNfzkrZiMl/33V1e19KIGS0jNGUYTAvheO/jU8XdE6uw2Ai9IFxlsyAoaxUydQkZyGWSrrx6xIkN+D0Kl8m55YpzHKwdJ2ugr90In7o8oyvFC98IqdbR1BcG+dQt5gX5gFqH+klIQ7XyYAgXSOctxoW2o+3HQYC2DIKzmqyBZwLHvpyKuRqcM3Q13e2hCve4hg09c8umRx+y7Xz9QRoBVYPBTKw3yrX6zkMixTy16Z3n54+YEJHQ16fXubfzQeNI/B0/kwVe9MSPeOpYHP1AQSv/GxNZWi6pAW7smLb9hKzzRHdQKHKwPfMluqDfKzxW4Y1x6kHFUzwX0hI3fNGtrs5agg+phC23Xe4nEeROP0cG4SX9Va3Dow6MjYIkC/J7LOzpRDKIEzRaLdFN1Dkdte7+tj9Lq3CZQ0mPGYGLr42dYGFkEpYmZkqRl5B7PSH9DlajtEQcIfGLO8A7onYntQlLTVFa3oJerLb2dT0lRYT12gTxHwfiBtzSiQCswMe544j/g4cM01/ImMXEqRuLBc9XN1209T2fw5xn04/eMtKRgcXmyp/17hTAoPgaBQ9RQ88LjT3Rccs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
